//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR30_3_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CookingBook
    {
        public int BookCode { get; set; }
        public Nullable<int> DishCode { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public Nullable<int> ProductScope { get; set; }
    
        public virtual Dishs Dishs { get; set; }
        public virtual Products Products { get; set; }
    }
}
