//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR30_3_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dishs()
        {
            this.CookingBook = new HashSet<CookingBook>();
        }
    
        public int DishCode { get; set; }
        public string DishType { get; set; }
        public Nullable<int> DishWeight { get; set; }
        public string PreparationOrder { get; set; }
        public Nullable<int> CaloryCount { get; set; }
        public Nullable<int> CarbCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CookingBook> CookingBook { get; set; }
    }
}
